In [2]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
addition=A+B
print("Addition:\n",addition)
subtraction=A-B
print("\nSubtraction:\n",subtraction)
multiplication=A*B
print("\nMultiplication:\n",multiplication)
division=A/B
print("\nDivision:\n",division)
dot_product=np.dot(A,B)
print("\nDot Product:\n",dot_product)
transpose_A=A.T
print("\nTranspose of A:\n",transpose_A)
transpose_B=B.T
print("\nTranspose of B:\n",transpose_B)

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Multiplication:
 [[ 5 12]
 [21 32]]

Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

Dot Product:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Transpose of B:
 [[5 7]
 [6 8]]
